# Generated by Django 3.1.14 on 2023-12-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200317_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='media/profile_pics/temp.png', upload_to='profile_pics'),
        ),
    ]
